setup:
    database: /home/b21user/nathanc/Pypline3/db/pypline3.db
    logfile: /home/b21user/nathanc/Pypline3/logs/Pypline3.log
    poll_dir: /dls/b21/data/
    redis_host: localhost
    redis_port: 6379
settings:
    dwell_time: 5.0
    number_digits_in_output_index: 5
    time_out_time: 600.0
    existing_dat_file_directory: processed
    dat_output_dir: /processing/pypline/
    raw_dat_dir: raw_dat/
    av_dat_dir: av_dat/
    sub_dat_dir: sub_dat/
    unsub_dir_pre: b21-
    unsub_dir_post: .unsub
    visit_id_pv: BL21B-EA-EXPT-01:ID
dat_data:
    lowq_lo: 0.0136
    lowq_hi: 0.0272
    highq_lo: 0.950
    highq_hi: 0.990
    lowq_deadband: 1.02
    highq_deadband: 0.95
    sec_buffer_window_size: 11
